### ISSUE TITLE
Parallel execution

### ISSUE THREAD

**Issue by eldoy** [eldoy/fiks#13]
We can use Promise.all to do parallel execution of actions like pull to speed things up.

**Comment by acmb** [comment]
Using `Promise.all` in our case is not direct as we're running `synchronous` functions, and I couldn't seem to find a quick workaround that would provide us with the expected behaviour.

For this reason and as discussed, I'm adding this to `BACKLOG.md` so we can invest a bit more time into this when it's more convenient.
