### ISSUE TITLE
Fiks pull stash

### ISSUE THREAD

**Issue by eldoy** [eldoy/fiks#8]
When doing git pull, you changes are stashed, and after the pull they are re-applied with git stash apply. The problem is when the stash is not empty from before, then you stash apply unwanted changes. Maybe it's better if pull just fails and you get an error message?

Please discuss solutions.

**Comment by acmb** [comment]
Hei, @eldoy!

My tests lead me to believe that `git stash apply` translates to `git stash apply 0`, applying the _**latest**_ stash, not all of them at once. This also seems to be the behaviour described in [this](https://opensource.com/article/21/4/git-stash#:~:text=You%20can%20reapply%20stashed%20changes,them%20to%20the%20working%20copy./#retrieving-stashed-changes) article.

![Screenshot 2024-06-10 at 15 54 37](https://github.com/eldoy/fiks/assets/48370302/7d9b44fa-cc36-493e-ba00-f9e250a6c568)

So, in practice, we'd be applying the stash we just created before `pull`, not including previous unwanted changes.
My only suggestion would be to consider the option of running `git stash pop` instead of `git stash apply`, so we would apply the latest stash and remove it simultaneously. At the same time, I fear using `pop` may lead to lost changes if we encounter some unexpected bug in `fiks`, so it is probably safer to use `apply`.

Did I misunderstand the issue in any way? Please let me know your thoughts.

**Comment by eldoy** [comment]
The problem is that you might have done git stash before and forgot to re-apply. When we do git stash, nothing new happens, but when we do git stash apply, then _the old stash_ is being applied. 

Maybe the safest is to abort the pull if we have uncommitted changes? The alternative would be to do git stash clear before apply. I'm ok with it, but it's risky.

**Comment by acmb** [comment]
Oh, got it!

The scenario is: we're doing `pull` but we don't have changes. Meaning our git stash does nothing and in that case we shouldn't apply the latest stash, because it was not created in the context of our current operation. Did I get it right?

In that case, we could do something like this:

```js
var res = extras.get(`git -C ./${directory} stash`)
var stashed = res.includes('Saved working directory')

extras.get(`git -C ./${directory} pull --rebase`)

stashed && extras.get(`git -C ./${directory} stash apply`)
```

Meaning, we will only apply the latest stash if we actually stashed something before pulling.

What are your thoughts on this solution?

**Comment by eldoy** [comment]
Ok, if that works then that should solve it.
